# Generated by Django 6.0.2 on 2026-03-28 11:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('module', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('javascript', 'JavaScript'), ('sql', 'SQL / Databases'), ('dsa', 'Data Structures & Algorithms'), ('communication', 'Communication'), ('soft_skills', 'Soft Skills')], max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('resource_url', models.URLField(blank=True)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='unlocks', to='ai_recommendations.topic')),
            ],
            options={
                'ordering': ['module', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('max_score', models.FloatField(default=100)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('wrong_topics', models.JSONField(blank=True, default=list)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='ai_recommendations.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_type', models.CharField(choices=[('topic', 'Revisit Topic'), ('exercise', 'Practice Exercise'), ('article', 'Read Article'), ('path', 'Learning Path'), ('tip', 'AI Tip')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('url', models.CharField(blank=True, max_length=500)),
                ('priority', models.PositiveSmallIntegerField(default=5)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_recommendations.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPracticeCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exercise_count', models.PositiveIntegerField(default=1)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_completions', to='ai_recommendations.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='UserWeakArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weakness_score', models.FloatField(default=0.5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weak_areas', to='ai_recommendations.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weak_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-weakness_score'],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
