# Generated by Django 6.0.2 on 2026-04-04 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentrecord',
            options={},
        ),
        migrations.AddField(
            model_name='subscription',
            name='duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='app1.paymentrecord'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('manual', 'Manual')], default='razorpay', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='expired', max_length=20),
        ),
    ]
