# Generated by Django 6.0.2 on 2026-05-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_subscription_plan_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan_type',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='free', max_length=20),
        ),
    ]
