# Generated by Django 6.0.2 on 2026-03-25 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_contactmessage_id_alter_livesession_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total_marks', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
       
        
        
       
        migrations.AddField(
            model_name='testresult',
            name='skipped_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='wrong_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='correct_answers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='time_taken',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='total_questions',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.test'),
        ),
    ]
