# Generated by Django 6.0.2 on 2026-03-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_test_alter_testresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.CharField(choices=[('basics', 'Python Basics Test'), ('functions', 'Python Function Test'), ('loops', 'Python Loop Test'), ('general', 'Python Test')], default='basics', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
