# Generated by Django 6.0.2 on 2026-03-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_test_category_alter_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='module',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java')], default='basics', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.CharField(choices=[('basics', 'Basics'), ('functions', 'Functions'), ('loops', 'Loops'), ('oop', 'OOP'), ('general', 'Final Test')], max_length=20),
        ),
    ]
