# Generated by Django 6.0.2 on 2026-03-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_test_module_alter_test_category'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='test',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('sql', 'SQL'), ('js', 'JavaScript'), ('cpp', 'C++'), ('dsa', 'Data Structures')], default='python', max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.CharField(choices=[('basics', 'Basics Test'), ('functions', 'Function Test'), ('loops', 'Loop Test'), ('oop', 'OOP Test'), ('general', 'Full Test')], default='basics', max_length=20),
        ),
    ]
