# Generated by Django 6.0.2 on 2026-03-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_test_module_test_language_alter_test_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='desc1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='desc2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='desc3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='desc4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='desc5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
