# Generated by Django 6.0.2 on 2026-03-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_testresult_desc1_testresult_desc2_testresult_desc3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='score',
        ),
        migrations.AddField(
            model_name='test',
            name='pass_percentage',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='testresult',
            name='marks',
            field=models.FloatField(default=0),
        ),
    ]
