# Generated by Django 6.0.2 on 2026-03-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_testresult_score_test_pass_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='pass_percentage',
            field=models.FloatField(default=0),
        ),
    ]
