# Generated by Django 6.0.2 on 2026-03-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_test_pass_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('sql', 'SQL'), ('js', 'JavaScript'), ('cpp', 'C++'), ('dsa', 'Data Structures'), ('comm', 'communication'), ('apti', 'aptitude'), ('interv', 'interview'), ('tech', 'technical')], default='python', max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='pass_percentage',
            field=models.IntegerField(default=40),
        ),
    ]
