# Generated by Django 6.0.2 on 2026-03-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_test_language_alter_test_pass_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='marks',
            new_name='obtained_marks',
        ),
        migrations.AddField(
            model_name='testresult',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('sql', 'SQL'), ('js', 'JavaScript'), ('cpp', 'C++'), ('dsa', 'Data Structures'), ('comm', 'Communication'), ('apti', 'Aptitude'), ('interv', 'Interview'), ('tech', 'Technical')], default='python', max_length=20),
        ),
    ]
